### ISSUE TITLE
xGRviaGenomicAnno

### ISSUE THREAD

**Issue by hfang-bristol** [hfang-bristol/XGR#1]

**Comment by mshicuhk** [comment]
Hi Hai,

I have come across the following error when using `xGRviaGenomicAnno` with `GR.annotation = "ENCODE_TFBS_ClusteredV3_CellTypes"`:

> Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘reduce’ for signature ‘"list"’

Do you have any idea about this problem?

P.S. my script is 
` a <- xGRviaGenomicAnno(data.file = mydat, format.file = "data.frame", resolution = "hybrid", GR.annotation = "ENCODE_TFBS_ClusteredV3_CellTypes")`

Many thanks!
Leon

**Comment by hfang-bristol** [comment]
Thanks Leon. Actually you can not select this genomic annotation directly as 'ENCODE_TFBS_ClusteredV3_CellTypes' is a list of a list of GR objects. I should remove it. I recommend you to use 'Uniform_TFBS' instead. If you are interested in a specific cell type, please refer to http://galahad.well.ox.ac.uk/XGR/XGR_GWAS_SNPs.html#5322_encode_tfbs_analysis for details. 

Best, Hai

**Comment by mshicuhk** [comment]
Gotcha. Thank you very much, Hai!

Leon
