### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by Acribbs** [hfang-bristol/XGR#10]
Hi,

I see that the CRAN version has been removed and archived. I therefore tried to install using Biocmanager:

```
BiocManager::install("XGR", dependencies=T)
```

but get the following issues while trying to install to R v3.6.2

```
Warning message:
package ‘XGR’ is not available (for R version 3.6.2) 
```

Any help would be great 

Thanks

**Comment by hfang-bristol** [comment]
XGR currently not available from CRAN. Hope it will be resolved in the future. 
Please install via
BiocManager::install("remotes")
BiocManager::install("hfang-bristol/XGR", dependencies=T)

**Comment by Acribbs** [comment]
Perfect worked thanks.
