### ISSUE TITLE
GO annotation data versions and discrepancy

### ISSUE THREAD

**Issue by davetgerrard** [hfang-bristol/XGR#2]
Great software, thanks for writing it.

I noticed that a particular gene was missing from a certain GO term, even though it was in my enriched set and I know it is annotated to the term. My 'bug' is really a query and has two parts:-

1. How do I find the version of the annotation set that you have created and I am using?
2. Why is this particular gene (PDX1) missing from the annotation set that can currently be loaded?

Code used to demonstrate that the gene is not linked to the GO term:-

 
```
# I'm interested in this GO term :- 
# GO:0031016 pancreas development
# http://amigo.geneontology.org/amigo/term/GO:0031016  
# includes PTF1A and PDX1 transcription factors amongst others.

# I noticed that XGR is not listing PDX1 in the set of genes for this term 
# even though it is in my list.  
# I wanted to know if PDX1 is included within the representation of the
#  GeneOntology Biological Process annotation set used by XGR.
# It appears that it is not even though I would expect PDX1 to 
# have been annotated under Pancreas development for many years.

library(XGR)

# to load XGR's data for human GOBP
org.Hs.egGOBP <- xRDataLoader(RData='org.Hs.egGOBP')
# see http://galahad.well.ox.ac.uk/bigdata_dev/man/org.Hs.egGOBP.html
# what is the structure of org.Hs.egGOBP
head(org.Hs.egGOBP$gs)
head(org.Hs.egGOBP$set_info)

# XGR is using Entrez IDs (not a great choice as they are numbers...). Anyway,
# From GeneCards: External Ids for PDX1 Gene
# HGNC: 6107 Entrez Gene: 3651 Ensembl: ENSG00000139515 OMIM: 600733 UniProtKB: P52945
ez_PDX1 <- 3651      # This is in GO but XGR cannot link it to GO:0031016
ez_PTF1A <- 256297   # as a +ve control. I know this is in GO and XGR.

org.Hs.egGOBP$gs['GO:0031016']     # 

c(ez_PTF1A, ez_PDX1)  %in%  org.Hs.egGOBP$gs[['GO:0031016']]    # gives c(TRUE , FALSE)
```

**Comment by hfang-bristol** [comment]
Thanks for your interest and the codes shared.
Our annotations from GO to genes (without IEA GO evidence code) are directly downloaded from NCBI Gene (http://galahad.well.ox.ac.uk/bigdata_dev/man/org.Hs.egGOBP.html; updated since this May), mainly due to its high-quality annotation (sourced from GOA). In terms of PDX1 (https://www.ncbi.nlm.nih.gov/gene/3651), there is no association with 'pancreas development' ('GO:0031016').

**Comment by davetgerrard** [comment]
Hmmm, that's weird.  

I can see that at https://www.ncbi.nlm.nih.gov/gene/3651, there is no association with 'pancreas development' ('GO:0031016') although other IEA associations are listed.

BUT, if you follow the link there back to GOA and search for the gene 
http://www.ebi.ac.uk/QuickGO/GProtein?ac=P52945
It does list  'pancreas development' ('GO:0031016')  as an annotation at IEA level.

Sorry, this no longer seems to be an XGR issue, rather a difference between NCBI and EBI representations of the Gene Ontology. I don't think this is a recent annotation, this gene has been associated with this function for quite a few years.

**Comment by hfang-bristol** [comment]
In XGR, we are only supporting annotations not evident from IEA. Thanks!
