### ISSUE TITLE
Ontology won't download 

### ISSUE THREAD

**Issue by annajbott** [hfang-bristol/XGR#4]
Hi,
I've used xEnricherGenes in the past and its worked fine. Went to use again recently and the ontologies won't load (MsigdbC2KEGG and MsigdbC2REACTOME). 
Getting error messages:
> ontology <- "MsigdbC2KEGG"
> eTerm <- xEnricherGenes(data = data_symbols, background = background_symbols, ontology = ontology)

Start at 2019-06-17 18:39:17

Load the ontology MsigdbC2KEGG and its gene annotations (2019-06-17 18:39:17) ...
Start at 2019-06-17 18:39:17

Attempt to download from https://github.com/hfang-bristol/RDataCentre/blob/master/Portal/org.Hs.egMsigdbC2KEGG.RData?raw=true (at 2019-06-17 18:41:00)
Attempt to download from http://galahad.well.ox.ac.uk/bigdata/org.Hs.egMsigdbC2KEGG.RData (at 2019-06-17 18:41:00)
Attempt to download from http://galahad.well.ox.ac.uk/bigdata/org.Hs.egMsigdbC2KEGG.RData (at 2019-06-17 18:42:43)
'org.Hs.egMsigdbC2KEGG' CANNOT be loaded (at 2019-06-17 18:44:26)

End at 2019-06-17 18:44:26
Runtime in total is: 309 secs

Error in data.frame(from = "root", to = nodes$name) : 
  arguments imply differing number of rows: 1, 0

-----

Are the ontologies no longer supported? Or is it something on my end?

Thanks,
Anna

**Comment by dtlloyd96** [comment]
Hi, 

I have gotten the same error message starting from around this morning at 8:30 am EST. I am glad to know that it is not on my end but any fix would be helpful. It has broken all code that xEnricherGenes is in.

**Comment by hfang-bristol** [comment]
Thank you for the message. It is due to the temporary down of our web server (now restored).

**Comment by annajbott** [comment]
Brilliant working now thanks!
