### ISSUE TITLE
installation problems with XGR

### ISSUE THREAD

**Issue by FelixThaler** [hfang-bristol/XGR#7]
I'm trying to install the XGR package on Rstudio using the recommended code: 

if(!("BiocManager" %in% rownames(installed.packages()))) install.packages("BiocManager")
BiocManager::install("XGR", dependencies=T)
## reload the installed package
detach(package:XGR, unload=T)
library(XGR)

after a while r asks if i want to uptade a/s/n:

i typed a  and after some "trying URL...." i got the following Error message:

package ‘graph’ successfully unpacked and MD5 sums checked
package ‘Rgraphviz’ successfully unpacked and MD5 sums checked
Error in read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) : 
  cannot open the connection
In addition: Warning messages:
1: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 8957952 != reported length 18270741
2: In unzip(zipname, exdir = dest) : error 1 in extracting from zip file
3: In read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) :
  cannot open compressed file 'BH/DESCRIPTION', probable reason 'No such file or directory'

does anyone know how to fix this?
thanks

**Comment by hfang-bristol** [comment]
BiocManager::install("XGR", dependencies=T)

After that, suggest not updating (n).
The problem is not directly related to XGR but the existing packages installed previously.
